/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.pm2.autochess;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AppMOCK classUnderTest = new AppMOCK();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
